### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by magistau** [srijanshetty/zsh-pip-completion#1]
I installed it with antigen and it doesn't seem to work

**Comment by srijanshetty** [comment]
Hey @MinerChAI could you kindly expand on the issues you are facing? ZSH version, antigen version? I don't use antigen anymore and used basked in completions that come in the community zsh-completions

**Comment by magistau** [comment]
I could, but the thing is, I dunno what info do you need. If you tell me what do you need, I’ll give you that. I’m quite newbie in zsh and not yet familiar with zsh development.

**Comment by srijanshetty** [comment]
@MinerChAI, if you're a newbie at ZSH, I'll suggest you install [prezto](https://github.com/sorin-ionescu/prezto), I'm a maintainer of prezto and it's batteries included, so you'll get completions for pip et al out of the box. Follow the instructions and post and issues you find in the Issue tracker for prezto and I'll help you out for sure!
